server:
  port: 8080 #springBoot项目访问端口

spring:
  activemq:
    broker-url: tcp://43.143.78.169:61616  #你activeMQ的ip和端口号
    user: admin   #activeMq账号
    password: admin #activeMq密码
    queue-name: active.order #队列名
    pool:
      enabled: true       #连接池启动
      max-connections: 10 #最大连接数


